spring:
  main:    web-application-type: none
  data:
    mongodb:
      uri: mongodb+srv://${mongodb-altas.login}:${mongodb-altas.passwd}@${mongodb-altas.cluster-domain}/stock?retryWrites=true&w=majority
      
stock-dashboard:
  stock-list: >
    aapl,
    msft,
    amzn,
    googl,
    fb,
    baba,
    v,
    jnj,
    wmt,
    tsm,    
    pg,
    ma,
    jpm,
    unh,
    hd,
    tsla,
    intc,
    nvda,
    vz,
    t,
    dis,
    adbe,
    pypl,
    mrk,
    pfe,
    bac,
    ko,
    csco,
    cmcsa,
    pep